# Generated by Django 5.2.12 on 2026-03-15 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('created_by', models.UUIDField(blank=True, help_text='Creator user ID', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='Updater user ID', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('name', models.CharField(help_text='Company name', max_length=255, unique=True)),
                ('code', models.CharField(help_text='Company code/identifier', max_length=50, unique=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax Identification Number', max_length=50, null=True)),
                ('currency', models.CharField(default='USD', help_text='Default currency (ISO 4217)', max_length=3)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'sys_company',
            },
        ),
        migrations.CreateModel(
            name='UserCompanyAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('created_by', models.UUIDField(blank=True, help_text='Creator user ID', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='Updater user ID', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default company for the user?')),
                ('company', models.ForeignKey(help_text='Company the user can access', on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='company.company')),
                ('user', models.ForeignKey(help_text='User who has access', on_delete=django.db.models.deletion.CASCADE, related_name='company_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Company Access',
                'verbose_name_plural': 'User Company Accesses',
                'db_table': 'sys_user_company_access',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
