MATERIAL_READ = "MATERIAL_READ"
MATERIAL_WRITE = "MATERIAL_WRITE"
MATERIAL_PRICE_MANAGE = "MATERIAL_PRICE_MANAGE"

PERMISSIONS = [
    (MATERIAL_READ, "Material Read"),
    (MATERIAL_WRITE, "Material Write"),
    (MATERIAL_PRICE_MANAGE, "Material Price Manage"),
]
