# Generated by Django 5.2.12 on 2026-03-16 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_basemodel_softdelete_and_user_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('target_model', models.CharField(help_text='The model name of the target object', max_length=100)),
                ('target_object_id', models.CharField(help_text='The ID of the target object', max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('OTHER', 'Other')], default='OTHER', help_text='The type of action performed', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detailed changes or payload')),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='SUCCESS', help_text='The result of the action', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requester', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('request_id', models.CharField(blank=True, help_text='Unique request ID for tracing', max_length=50, null=True)),
                ('company', models.ForeignKey(blank=True, help_text='The company context for this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Updater user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_model', 'target_object_id'], name='audit_audit_target__53d4dc_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx'), models.Index(fields=['created_by'], name='audit_audit_created_35c32f_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('username', models.CharField(help_text='The username used for the login attempt', max_length=150)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='SUCCESS', help_text='The status of the login attempt', max_length=20)),
                ('failure_reason', models.TextField(blank=True, help_text='The reason for login failure', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requester', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details')),
                ('company', models.ForeignKey(blank=True, help_text='The company context for this login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Updater user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='The user attempting to log in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Log',
                'verbose_name_plural': 'Login Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username'], name='audit_login_usernam_a1903e_idx'), models.Index(fields=['status'], name='audit_login_status_958c81_idx'), models.Index(fields=['created_at'], name='audit_login_created_15f14d_idx')],
            },
        ),
    ]
