# Generated by Django 5.2.12 on 2026-03-16 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_basemodel_softdelete_and_user_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleSwitch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('module_name', models.CharField(db_index=True, max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, help_text='If null, represents a global switch. If set, represents a company-specific override.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_switches', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Updater user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module Switch',
                'verbose_name_plural': 'Module Switches',
                'db_table': 'sys_module_switch',
                'unique_together': {('module_name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('value', models.JSONField(help_text='Typed config value stored as JSON')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('company', 'Company'), ('module', 'Module')], db_index=True, default='global', max_length=20)),
                ('module', models.CharField(blank=True, help_text='Required if scope is module', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('company', models.ForeignKey(blank=True, help_text='Required if scope is company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Updater user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Config',
                'verbose_name_plural': 'System Configs',
                'db_table': 'sys_system_config',
                'unique_together': {('key', 'scope', 'company', 'module')},
            },
        ),
    ]
